import { Store, Item, Inventory } from '../types';

export const stores: Store[] = [
  { id: 'tnt-metrotown', name: 'T&T Supermarket Metrotown', lat: 49.2276, lng: -122.9998 },
  { id: 'tnt-richmond',  name: 'T&T Supermarket Richmond',  lat: 49.1666, lng: -123.1336 },
  { id: 'tnt-downtown',  name: 'T&T Supermarket Downtown',  lat: 49.2827, lng: -123.1207 },
  { id: 'superstore-bby', name: 'Real Canadian Superstore Burnaby', lat: 49.2488, lng: -122.9805 },
];

export const items: Item[] = [
  { id: 'F01',  name: 'Fresh Durian (7lbs)',                    category: 'Exotic Fruit' },
  { id: 'F02',  name: 'Specialty Lychee (2lb)',                 category: 'Exotic Fruit' },
  { id: 'F03',  name: 'Dragon Fruit (2.6lb)',                   category: 'Exotic Fruit' },
  { id: 'F04',  name: 'Red Dragon Fruit (1.5lbs)',              category: 'Exotic Fruit' },
  { id: 'F05',  name: 'Sun Mango (2.5lb)',                      category: 'Tropical Fruit' },
  { id: 'F06',  name: 'Fresh Banana (~3lbs)',                   category: 'Tropical Fruit' },
  { id: 'F07',  name: 'Fuji Apple (2.8lbs)',                    category: 'Fruit' },
  { id: 'F08',  name: 'Asian Golden Pear (2.8lbs)',             category: 'Fruit' },
  { id: 'F09',  name: 'Seedless Green Grape (~2.5lb)',          category: 'Fruit' },
  { id: 'F10',  name: 'Cherry (2lb)',                           category: 'Fruit' },
  { id: 'F11',  name: 'Blueberry',                              category: 'Fruit' },
  { id: 'F12',  name: 'Strawberry (1lb)',                       category: 'Fruit' },
  { id: 'V01',  name: 'Shanghai Bok Choy (1.5lb)',              category: 'Asian Vegetables' },
  { id: 'V02',  name: 'Gai Lan (~1.5lb)',                       category: 'Asian Vegetables' },
  { id: 'V03',  name: 'Yu Choy (~1.5lb)',                       category: 'Asian Vegetables' },
  { id: 'V04',  name: 'Bitter Melon (1.5lb)',                   category: 'Asian Vegetables' },
  { id: 'V05',  name: 'Lotus Root (1.5lb)',                     category: 'Asian Vegetables' },
  { id: 'V06',  name: 'Large Taro (~3lb)',                      category: 'Root Vegetables' },
  { id: 'V07',  name: 'Japanese Sweet Potato / Yam (2.5lb)',    category: 'Root Vegetables' },
  { id: 'V08',  name: 'Hawaii Purple Sweet Potato / Yam (2.5lb)', category: 'Root Vegetables' },
  { id: 'V09',  name: 'White Radish (~2.5lb)',                  category: 'Root Vegetables' },
  { id: 'V10',  name: 'Green Onion (1bunch)',                   category: 'Aromatics' },
  { id: 'V11',  name: 'Ginger (1lb)',                           category: 'Aromatics' },
  { id: 'V12',  name: 'Lemon Grass (2-3pcs)',                   category: 'Herbs' },
  { id: 'V13',  name: 'Cilantro (1bunch)',                      category: 'Herbs' },
  { id: 'V14',  name: 'Bamboo Shoot (1.5lb)',                   category: 'Asian Vegetables' },
  { id: 'M01',  name: 'Organic Enoki Mushroom (150g)',          category: 'Mushrooms' },
  { id: 'M02',  name: 'Shiitake Mushrooms (1.6lbs)',            category: 'Mushrooms' },
  { id: 'M03',  name: 'Korean King Oyster Mushroom (300g)',     category: 'Mushrooms' },
  { id: 'FZ01', name: 'T&T Durian (454g)',                      category: 'Frozen' },
  { id: 'FZ02', name: 'Frozen Golden Pillow Durian (8lb)',      category: 'Frozen' },
  { id: 'FZ03', name: 'Vefa Frozen Lemongrass (250g)',          category: 'Frozen' },
  { id: 'SS1',  name: 'Vine Tomatoes (1.5lb)',                  category: 'Vegetables' },
  { id: 'SS2',  name: 'Crown Broccoli (1.5lb)',                 category: 'Vegetables' },
  { id: 'SS3',  name: 'Napa (~5lb)',                            category: 'Vegetables' },
];

export const inventory: Inventory[] = [
  // tnt-metrotown
  { storeId: 'tnt-metrotown', itemId: 'F01',  price: 13.88, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'F02',  price:  3.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'F03',  price:  2.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'F07',  price:  2.29, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'F09',  price:  4.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'F11',  price:  3.98, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V01',  price:  1.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V02',  price:  2.29, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V04',  price:  1.98, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V05',  price:  2.49, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V10',  price:  0.63, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'V11',  price:  1.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'M01',  price:  2.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'M02',  price:  3.88, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'FZ01', price: 16.99, inStock: true },
  { storeId: 'tnt-metrotown', itemId: 'FZ02', price:  5.99, inStock: true },
  // tnt-richmond
  { storeId: 'tnt-richmond',  itemId: 'F01',  price: 13.88, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'F04',  price:  5.88, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'F05',  price:  5.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'F06',  price:  0.89, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'F08',  price:  1.69, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V03',  price:  1.68, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V06',  price:  1.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V07',  price:  2.88, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V08',  price:  5.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V12',  price:  1.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'V14',  price:  6.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'M02',  price:  3.88, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'M03',  price:  3.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'FZ02', price:  5.99, inStock: true },
  { storeId: 'tnt-richmond',  itemId: 'FZ03', price:  1.34, inStock: true },
  // tnt-downtown
  { storeId: 'tnt-downtown',  itemId: 'F02',  price:  3.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'F10',  price:  9.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'F12',  price:  6.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'V01',  price:  1.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'V09',  price:  1.09, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'V10',  price:  0.63, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'V11',  price:  1.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'V13',  price:  1.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'M01',  price:  2.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'M03',  price:  3.99, inStock: true },
  { storeId: 'tnt-downtown',  itemId: 'FZ01', price: 16.99, inStock: true },
  // superstore-bby
  { storeId: 'superstore-bby', itemId: 'F07',  price: 2.49, inStock: true },
  { storeId: 'superstore-bby', itemId: 'F09',  price: 5.49, inStock: true },
  { storeId: 'superstore-bby', itemId: 'F11',  price: 4.49, inStock: true },
  { storeId: 'superstore-bby', itemId: 'F12',  price: 5.99, inStock: true },
  { storeId: 'superstore-bby', itemId: 'SS1',  price: 2.99, inStock: true },
  { storeId: 'superstore-bby', itemId: 'SS2',  price: 2.49, inStock: true },
  { storeId: 'superstore-bby', itemId: 'SS3',  price: 1.99, inStock: true },
  { storeId: 'superstore-bby', itemId: 'V10',  price: 0.99, inStock: true },
  { storeId: 'superstore-bby', itemId: 'V11',  price: 2.29, inStock: true },
];
